openapi: 3.0.0
info:
  title: Cart Service
  version: 1.0.0
  description: A simple cart service.
paths:
  /cart/{userId}:
    get:
      summary: Get a user's cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The user's cart.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    delete:
      summary: Empty a user's cart
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The cart was emptied successfully.
  /cart:
    post:
      summary: Add an item to the cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemRequest'
      responses:
        '201':
          description: The item was added successfully.

components:
  schemas:
    Cart:
      type: object
      properties:
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
          format: int32
    AddItemRequest:
      type: object
      properties:
        userId:
          type: string
        item:
          $ref: '#/components/schemas/CartItem'
